name: Manual deployments for all envs
on:
  workflow_dispatch:
    inputs:
      env:
        description: Select then env you want to deploy your SPA.
        options:
          - dev
          - qa
          - stage
          - prod
        default: dev
        required: true
        type: choice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install node modules
        run: npm install

      - name: Build package
        run: npm run build

      - name: Deploy package
        run: npx @spaship/cli@latest deploy --apikey=${{ secrets.SPASHIP_API_KEY }} --env=${{ secrets.SPASHIP_DEPLOY_URL }}${{ inputs.env }} --ref=$(node -p "require('./package.json').version")
